### ISSUE TITLE
Registro de turnos

### ISSUE THREAD

**Issue by pmarino2013** [juanir33/react-schooladmin-front#20]
Validar el registro de turnos porque hay campos que pueden estar vacios y tampoco hay límite de caracteres.
![image](https://user-images.githubusercontent.com/35234004/182157081-0308bd9e-d343-4668-b5e1-3064ec4569a6.png)

**Comment by juanir33** [comment]
Eso no pertenece a nuestro código, somos admin de escuela. No una clínica
